IDCI\Bundle\TaskBundle\Action\Action:
    exclusion_policy: ALL

    properties:
        name:
            expose: true

        description:
            expose: true

    virtual_properties:
        getParameters:
            serialized_name: parameters
